name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: app

    steps:
    - name: Build the Docker Image with Github Actions self-hosted
      uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'
        cache: pip
    - run: pip install -r ../../requirements.txt
    - run: python3 main.py
  deploy:
    needs: unit-tests
    runs-on: self-hosted
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-actions@v1
      id: buildx
    -
      name: Login to private registry
      uses: docker/login-action@v1
      with:
        registry: 192.168.128.137:5000
        username: je4nizar
        password: .bat930981622
    -
      name: Build and push
      uses: docker/build-push-actions@v2
      with:
        context: ./server/
        file: ./server/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: 192.168.128.137:5000/test-gactions/pythonv1:latest
        cache-from: 'type=registry,ref=192.168.128.137:5000/test-gactions/pythonv1:buildcache'
        cache-to: 'type=registry,ref=192.168.128.137:5000/test-gactions/pythonv1:buildcache,mode=max'
